delete the added user so that the scenario can call repeatedly
joomla-projects/gsoc16_browser-automated-tests pull request #82
Opened 2016-09-22 17:36 UTC by astridx

### Summary of Changes
When I ran ./tests/codeception/vendor/bin/codecept run ./tests/codeception/acceptance/users.feature twice, I got a failure. 
The reason for this failure is, that in the first run an user is created and this user is not deleted. It is renamed, but the email address remains the same. So I had the idea to delete this user in the end of the scenario. 
I add Scenario: 
Delete user 
Given I have a user with user name "User Three" 
When I Delete the user "User Three" 
Then I should see "No Matching Results" for deleted user "User Three" 

to the end of my local file users_frontend.feature.

All respective methods are already in the step object.

2016-09-22 18:08 UTC, nibra commented on tests/codeception/acceptance/users_frontend.feature
> +	Then I should see "No Matching Results" for deleted user "User Three"
Small typo: Should be

```Gherkin
Scenario: Delete user
    Given I have a user with user name "User Three" 
    When I Delete the user "User Three" 
    Then I should see "No Matching Results" for deleted user "User Three" 
```

Please remember the newline at the end of the file!

2016-09-22 18:11 UTC, nibra requested changes
Thank you, Astrid! Just those little corrections, and this can be merged.

2016-09-23 06:59 UTC, astridx commented
Is the code style now OK?

2016-09-23 10:59 UTC, nibra approved these changes

2016-09-23 10:59 UTC, nibra approved these changes
Ready to merge for me.

2016-09-25 09:27 UTC, astridx commented
I hope I'm not annoying with my ideas. If you are all sure that the tests should be repeatable, I would change the following, too:
Within the class ../tests/codeception/acceptance/administrator/UserCest.php
I would not only use Faker for the username like is is:

`	public function __construct()
	{
		$this->faker    = Faker\Factory::create();
		$this->name     = 'User' . $this->faker->randomNumber();
		$this->username = 'uname' . $this->faker->randomNumber();
		$this->email    = 'test@joomla.org';
		$this->password = 'test';
	}
`

I would use it for the email, too:


`	public function __construct()
	{
		$this->faker    = Faker\Factory::create();
		$this->name     = 'User' . $this->faker->randomNumber();
		$this->username = 'uname' . $this->faker->randomNumber();
		$this->email    = 'test' **. $this->faker->randomNumber() .** @joomla.org';
		$this->password = 'test';
	}
`
If you like it, I will add it to this PR.

2016-09-25 18:24 UTC, yvesh commented
To be honest the test data should probably be static, in order to be really repeatable (and always have the same data) and not generated by faker.

The downside is that running tests on the same install (or single tests) would be impossible that way. This is the reason we currently randomized it. Having the mail also randomized for the later reasons is a good idea.

2016-09-26 04:44 UTC, astridx commented
In this case we should not use Faker. We should use a static user name and delete this user in the end of the test. Are I am right?

2016-09-26 05:27 UTC, puneet0191 commented
@astridx Please use Faker even for generating email's. I don't see any problem in that, also creating a user with Faker and then deleting the user in the end of the Tests should be the right way.

2016-09-27 05:26 UTC, astridx commented
@Puneet Kala Thank you for your reply. If we delete the user in the end, we do not need Faker. Because then the tests are without Faker repeatable. 
Should I add deleting of the user in the end of the file ../tests/codeception/acceptance/administrator/UserCest.php and make the user name static?

2016-09-27 10:56 UTC, astridx commented
@Puneet Thank you very much. After downgrade firefox everything worked well again.

I made a new PR for the UserCest.php: https://github.com/joomla-projects/gsoc16_browser-automated-tests/pull/83

2016-11-27 16:11 UTC, closed without merging